language: python
python:
      - "3.7"
services:
      - mysql
env:
      -DJANGO=3.1.3 DB=mysql
install:
      - pip install -r requirements.txt
before_script:
      - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('fn37v9xn396jj') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
      - sudo service mysql restart
      - mysql -e 'create database test;' -u root -pfn37v9xn396jj
script:
      - python pomodoro/manage.py test
#       - cd pomodoro && py.test
#       - cd pomodoro && python manage.py test
      - cd pomodoro && py.test --ignore=timer/tests/test_tracker.py --ignore=timer/tests/test_api.py
# deploy:
#   provider: releases
#   api_key:
#         secure: ${GH_TOKEN}
#   file: "travis_report"
#   skip_cleanup: true
#   on:
#     tags: true
deploy:
  # Use Github pages deploy process
  provider: pages
  # Keep builded pages
  skip-cleanup: true
  # Directory where your generated files are located
  local_dir: public
  # Github security/auth token
  github-token: ${GH_TOKEN}
  # Incremental commit to keep old build/files from previous deployments
  keep-history: true
  # Git branch on which it should deploy (master, gh-pages, foo...)
  target_branch: gh-pages
  on:
    # Which branch on commit/push will trigger deployment
    branch: master
