language: python
python:
      - "3.7"
services:
      - mysql
env:
      -DJANGO=3.1.3 DB=mysql
install:
      - pip install -r requirements.txt
before_script:
      - mysql -e 'create database test;' -u root
script:
      - python pomodoro/manage.py test
deploy:
  provider: releases
  api_key:
        secure: ${GH_TOKEN}
  file: "travis_report"
  skip_cleanup: true
  on:
    tags: true
