language: python
python:
      - "3.7"
services:
      - mysql
env:
      -DJANGO=3.1.3 DB=mysql
install:
      - pip install -r requirements.txt
before_script:
      - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('fn37v9xn396jj') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
      - sudo service mysql restart
      - mysql -e 'create database test;' -u root -p fn37v9xn396jj
script:
      - python pomodoro/manage.py test
#       - cd pomodoro && py.test
#       - cd pomodoro && python manage.py test
      - cd pomodoro/timer && py.test --ignore=tests/test_tracker.py
deploy:
  provider: releases
  api_key:
        secure: ${GH_TOKEN}
  file: "travis_report"
  skip_cleanup: true
  on:
    tags: true
